[package]
name = "n-body-viewer"
version = "0.1.0"
authors = ["Lin Yinfeng <lin.yinfeng@outlook.com>"]
edition = "2018"

[dependencies]
threadpool = "*"
clap = "*"
log = "*"
env_logger = "*"
num_cpus = "*"
quick-error = "*"